### ISSUE TITLE
Forestry Drafts Not Going to Test Blog

### ISSUE THREAD

**Issue by hplakin** [sebs-scholarship/SSF-Blog#34]
**Describe the bug**
Forestry posts saved as "Draft ON" remain on forestry only and are not published to the test site.

**To Reproduce**
1. Go to a Forestry post
2. Click on Draft ON > save post
3. Go to test blog site
4. See only Draft OFF posts, no Draft ON posts

**Expected behavior**
Blog post published to test site when either Draft ON or Draft OFF

**Screenshots**

**Device info (please complete the following information):**
 - Device: [iPhoneXS, MacBook Pro]
 - Browser [Safari]

**Additional context**

**Comment by leviem1** [comment]
@hplakin Thanks, look like this was introduced by our recent pagination change #30. Since the pagination generator was made to work on production sites, it automatically hides drafts without an option to override. We're gonna have to prepend the drafts to the front-page if we're on the test site, _then_ append the current posts.

**Comment by leviem1** [comment]
For "Weekend Levi": https://shopify.dev/docs/themes/liquid/reference/tags/iteration-tags

**Comment by leviem1** [comment]
@hplakin Turns out we do display the blog posts, they're just added to the last page rather than the first as they were.

**Comment by hplakin** [comment]
Gotcha. Neat
